### ISSUE TITLE
Animated webp is not supported as input 

### ISSUE THREAD

**Issue by bobifle** [EttienneS/AnimatedTokenMaker#11]
The title says it all.
Animated gifs are supported, but for some reason, animated webp are not.
As webp becomes very popular, a lot of former gif and now in webp format.

example of webp:
https://static.wikia.nocookie.net/gwent/images/8/87/Harald_the_Cripple.gif/revision/latest/scale-to-width-down/220?cb=20180621073929

**Comment by EttienneS** [comment]
Thanks for the issue.  I will investigate.

**Comment by EttienneS** [comment]
Turns out this is a massive hassle :) webp is a very weird format and requires two additional tools to even be able to function webpmux and dwebp.

As this is not something everyone will use I added the support but made those optional, if you try to use a webp source you will be prompted to get the tools if you do not have them.  Otherwise it should just work as any other source.

This is fixed in the latest release 1.1.2
